apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:  
  replicas: 2 
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpdapp
        image: padybuzz/custom_httpd:1.0.1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
#Service config
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 80
        
